### ISSUE TITLE
MultiMC crash on loading screen 

### ISSUE THREAD

**Issue by xlicer** [PG85/OpenTerrainGenerator#10]
I installed the latest stable version of OpenTerrainGenerator and I got [this crash](https://pastebin.com/wEMKpiAS). [Full logs](https://pastebin.com/kaeVXTyA) I am using the MultiMC launcher

**Comment by PG85** [comment]
Thanks for the report, have added this to the new bugs thread here https://www.reddit.com/r/openterraingen/comments/67uzha/mod_compatibility_bugs_report_them_here/

**Comment by PG85** [comment]
This should be fixed with v18, OTG now registers dimensions when it is creating them instead of reserving 100 dimensions at app start. A dev version of v18 is available here: https://cdn.discordapp.com/attachments/307111022257373185/313254639841705985/OpenTerrainGenerator-1.10.2-v18-2.jar

Please give it a try and tell me if that fixes the problems.

*A few notes for this version:

Should fix a whole bunch of dimension related bugs, mostly when creating/deleting dimensions and relogging and/or restarting the server. May also solve some biome registration related bugs when used with other mods that add biomes. Portal mechanics have been overhauled, dimensions should work much better now and each world can have its own portal frame materials defined in the worldconfig.

If you test the release and use the Dimensions pre-set or create/delete your own dimensions using /otg dim -l, /otg dim -c and /otg dim -d you'll want to change the portal material for each dimension in the world config. Otherwise they will all default to quartz and you'll only be able to visit the first two dimensions via a quartz portal.

**Comment by xlicer** [comment]
IT WORKS!!,

**Comment by PG85** [comment]
Awesome, thanks for the report :D

**Comment by PG85** [comment]
By the way, the official v18 is now available here: https://minecraft.curseforge.com/projects/open-terrain-generator/files/2419946. It contains a few more fixes than the one you have.
