### ISSUE TITLE
Request - [1.12.2] Ambient spawn rate config

### ISSUE THREAD

**Issue by KorDum** [PG85/OpenTerrainGenerator#123]
I created config in `<Biome>.bc`

```
SpawnAmbientCreatures: [{"mob": "bat", "weight": 10, "min": 8, "max": 8}, {"mob": "grovesprite", "weight": 1, "min": 1, "max": 1}, ... {"mob": "entity_deer", "weight": 1, "min": 1, "max": 2}]
```
It's work, but ambient mobs too much. Very much. Can I reduce spawn rate?

**Comment by PG85** [comment]
Hey, thanks for the feedback. That would be a new feature, OTG only adds the mobs to the vanilla mob spawning lists and lets MC do the spawning. For now you could try experimenting by adding more entries in the list with weights and low numbers, maybe even min/max 0 will work (not sure).

**Comment by KorDum** [comment]
Mobs can despawn themselves if conatinas canDespawn = false?
At the moment, I ran into the situation that vanilla parrots do not despawn at all.

**Comment by PG85** [comment]
Non-hostile creatures like cows etc aren't supposed to despawn, they are only unloaded (and sometimes they die). Otherwise your cows would disappear from your house too. I think parrots are meant to be persistent like that as well?

**Comment by KorDum** [comment]
I would like to have opportunities for flexible customization spawn for more "expirience" and diversity in daytime, if possible. If the creature has a flag `canSpawn = true`, then everything is fine: ambient minor animals (squirrel and beetles in my modpack) spawn and despawn, but in very large quantities. I'll lower them a chance spawn through RoughMobs mod now.

**Comment by PG85** [comment]
For MCW (a retired branch of TC/OTG) I actually made custom mob spawning mechanics where you could configure all kinds of stuff. It completely took over the mob spawning from vanilla. Would need something like that to make this happen. Won't have time for such a feature for a while though unfortunately. 

What would be really useful is if mob mod developers either make sure to inherit from the vanilla mob classes when creating custom mobs so that their mobs can be made to work with the vanilla or vanilla-like spawning mechanics or that they agree on a common implementation of a set of spawn rules/methods for mobs so that mods can spawn each other's mobs. Right now mob mods like mocreatures and lycanites appear to be doing their own spawning and have created their mobs in a way that is incompatible with the vanilla spawning mechanics (by not inheriting from the vanilla mob/entity classes).

**Comment by PG85** [comment]
You can check btw if a mob has implemented one of the vanilla mob classes by using /otg entities. It should show a list of all the entities available, including all the mobs. If an entity has a label behind its name (either (CREATURE), (MONSTER), (AMBIENT) or (WATERCREATURE) if I'm not mistaken) then it can be used in the respective spawn list in the biome config.
