### ISSUE TITLE
Pam's Harvestcraft: Fruit Trees Don't Generate

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#154]
Not sure if it's because harvestcraft doesn't detect OTG biomes or not, have not tried adding OTG biomes manually to the harvestcraft config (see attached pic) as I'm not sure what the resource locations would be?
![image](https://user-images.githubusercontent.com/9453952/38469700-07e4d5e0-3b51-11e8-9897-1c8c61eb1bbd.png)

**Comment by m1cr0man** [comment]
Looks like this is broken since the 28th of Feb, where Pam migrated the tree selection system to use Forge's biome registry.

This would be the [culprit line](https://github.com/MatrexsVigil/harvestcraft/commit/98ea69e77dac0c81884fbbc54d17a80ec1250896#diff-e085e6b4bcd485c00ea6940b343ef051R27), where the list of registered biomes is filtered by the names in the whitelist.

Without an entry in Forge's biome registry, there won't be a way to convince Harvestcraft to generate trees in BB/OTG biomes.

**Comment by PG85** [comment]
If HarvestCraft checks the biome registry before OTG registers the biomes (when the world is loaded), then you're right, this is a problem. There are more mods that make the assumption that all biomes are registered at app start and it looks like OTG is the only mod that breaks that rule, so I think OTG will have to provide the solution. We've been talking about a new mode for OTG, where you can select one OTG preset (overworld+dimensions), for which all biomes are registered at app start. During a session, only that preset can be used, and only pre-defined dimensions can be created/deleted. I won't be able to do that before the 1.13 update though I'm afraid. See #300.
