### ISSUE TITLE
Enhancement: BO3Tools for Forge

### ISSUE THREAD

**Issue by Guinaro** [PG85/OpenTerrainGenerator#18]
It would be great if we could get BO3Tools for forge. Best would be if we could also use mod blocks aswell.
Currently we need to create a basic form in a bucket server with terraincontrol, world edit, and bo3Tools. And afterwards change the needed blocks in a text file to implement mod blocks.
For trees this is somewhat workable, but I cannot imagine doing this for custom structures especially with the multitude of different mod blocks available.
Probably need to force a way to disregard on the fly generated blocks: like those of flat colored blocks, malisis blocks's, ...

**Comment by PG85** [comment]
Hey, I don't maintain BO3Tools so you'll have to ask RutgerKok for that. Personally I use worldedit, mcedit and TCEE but I understand that for a lot of people that's not good enough. I agree we could use some better BO3 editing tools but at the moment my time is stretched to the limit just working on OTG :(.

**Comment by Guinaro** [comment]
Is TCCE available for 1.10.2?

**Comment by PG85** [comment]
TCEE is a windows application, you can grab the latest version from here: https://github.com/PG85/TCEE/tree/master/Build. You can use TCEE to convert schematics to BO3's, it doesn't allow you to set a center point for the BO3 like BO3Tools does though, so you would have to place corner blocks in your schematic with your object in between centered the way you want it, then after converting the schematic to BO3's you'd remove the corner blocks from the bo3's manually. Also, TCEE slices schematics to 16x16 BO3's automatically and turns the slices into branches. That's handy for big schematics like structures that you would want to spawn with CustomStructure(), but for trees and rocks etc you would want to use CustomObject() and a 32x32 single BO3 with no branches. I'll update TCEE asap so that it let's you choose to export a BO3 as a single 16x16 BO3, single 32x32 BO3 or multiple 16x16 BO3s with branches configured.

For now I'll close this issue, you can keep an eye on the TCEE repo for a new commit, hopefully I'll be able to get to it in the next few weeks (lots of other coding stuff to do that has prio, sorry).
