### ISSUE TITLE
FuturePack & Roguelike Dungeons + OTG: Crash in terrain gen with protected blocks

### ISSUE THREAD

**Issue by Nonsanity** [PG85/OpenTerrainGenerator#193]
I've been testing combinations of mods to try and narrow down this crash, and so far it's only occurred when OTG, FuturePack, and Roguelike Dungeons are together. (I made a simple test pack with these three in the Twitch launcher.)

I'm making the bug report here because OTG shows up the the stacktraces and the others do not. However, as I mentioned above, all three seem to be needed to generate the crash. This may just be a coincidence, but I've run multiple tests so I'm confident enough to write this up.

One thing the FuturePack mod adds are dungeons (similar in their branching structure to Roguelike's) that have block protection applied to them from the start. This protection seems to be a key element in the crash, though by itself it causes no issues.

My guess as a programmer is that OTG may be placing blocks and then trying to read values from them, but isn't checking to make sure the block was actually placed when FuturePack's block protection prevents it's dungeon blocks from being overwritten. It's quite possible I'm wrong, but it's my first suggestion as to where to start looking. If it's correct, the probable solution would be to always test if the target block is the type you think it is before interacting with it, even if the same code just attempted to place it.

FuturePack & Roguelike Dungeons : No crashes - the two dungeons coexist fine when they overlap
FuturePack & OTG : No crashes - even when the frequency of the dungeons is set high
FuturePack & Roguelike & OTG - crashes where FP's and RD's dungeons overlap

To duplicate:
1) Make a 1.12.2 pack (Twitch launcher makes this easy) with OTG, FuturePack, and Roguelike Dungeons.
2) After an initial launch to create config files, edit fp.cfg to change hugeDungeon_spawnrate to 0.035 which will greatly increase the frequency of the block protected dungeons.
3) Create a new creative world (I used seed 17615047092345115) and fly around until you get a crash (I flew to 153, 114, 1074 near where RD and FP dungeons overlap).
4) To demonstrate the association with FP's protected dungeons, edit fp.cfg to change hugeDungeon_mindis to 100000. This prevents these dungeons from spawning during the test.
5) Create a new world with the same seed and go to the same location the crash occurred.

Hope this helps! Let me know if there's anything else I can do to help with this issue.

**Comment by PG85** [comment]
Hey @Nonsanity , thanks for reporting this and sorry for the late response. Since this issue is quite old, happens only when using very specific mods/settings, we've only had one report, and there is no crash log or stack trace included, I can't give this any prio atm. There have been a lot of changes to OTG and the other mods since this bug report though, please try a dev version of OTG v7 or v8 from the OTG Discord at #openterraingen (or wait for the release) and see if that solves the issue. Feel free to re-open this issue or create a new one if the problem remains. Please include a crash log, that should allow me to find the problem quickly, thanks!
