### ISSUE TITLE
ToughAsNails/MrCrayFish Conflict?

### ISSUE THREAD

**Issue by ItzKarlPvP** [PG85/OpenTerrainGenerator#207]
https://pastebin.com/pJ9YkR7Q
It has issue with tough as nails , when i remove tough as nails it gets issue with mrcrayfish vehicle mod...Help!

**Comment by PG85** [comment]
Hi @ItzKarlPvP, thanks for reporting this. I see you're also using MicDoodleCore (Galacticraft), which caused problems with OTG v6 / early v7, this was fixed with one of the later v7 dev versions. Please join us on the OTG Discord at #openterraingen and grab the latest dev version from the dev channel and try that, thanks! If you're having more problems with other mods, try asking on the Discord first. Feel free to re-open this issue or create a new one if you find more technical issues.
