### ISSUE TITLE
Feature: *.nbt files for Entities

### ISSUE THREAD

**Issue by LanToaster** [PG85/OpenTerrainGenerator#266]
If you could assign an NBT file to Entities would be Awesome
would make Exporting and Editing NBT data for Entities much Easier.

**Comment by PG85** [comment]
Thanks for reporting. I've only tested with .txt files recently, will test with .nbt as well.

**Comment by PG85** [comment]
Does this affect Forge and/or Spigot?

**Comment by LanToaster** [comment]
Also only tested on Spigot.

Currently it worked like this:
Blocks only Accepted NBT files, and Entities only TXT

**Comment by PG85** [comment]
Will need to implement either a library in the common layer for reading nbt files, or use forge/spigot-specific methods to read nbt files for each platform. Not as quick and easy as it sound, unfortunately. Since there is a way to work around this, will do this after 1.13. Will update the comments in the configs to clarify though.

**Comment by PG85** [comment]
Fixed by Authvin for 1.12.2 v9, also ported to 1.16 for 0.0.17, though spigot still needs some fixes (see #752 ).
