### ISSUE TITLE
Crash: /otg reload on spigot

### ISSUE THREAD

**Issue by Jishuna** [PG85/OpenTerrainGenerator#271]
Latest version of spigot 1.12.2 and Biome bundle with r26 breaks when using /otg reload

Log: https://pastebin.com/sNuseRhu

Causes an internal error from the command and then a crash when generating chunks afterwards.

**Comment by PG85** [comment]
Hey @Coll1234567, thanks for reporting this, will take a look at this for v8.

**Comment by PG85** [comment]
This is due to lots of changes for dynamic biome ids for v7. For Forge this command isn't available, and users have to reload the world to reload configs. What exactly should this command do though, I can't imagine it should allow you to add/delete biomes during a session? How/when would you use this?

**Comment by PG85** [comment]
For v8_r3, have disabled this command.

**Comment by Jishuna** [comment]
Is it feasible to have the command only reload the settings of already registered biomes without re-registering them.

**Comment by PG85** [comment]
That I can do, have added a fix in v8_r3, the command appears to work, will need some testing though.
