### ISSUE TITLE
Game crashes when entering/generating world after removing mod

### ISSUE THREAD

**Issue by AyumuTheDreamer** [PG85/OpenTerrainGenerator#281]
Title is self explanatory. Every time after i uninstalled the mod i crash, but reinstalling it fixes it. i just want a superflat/biomes o'plenty world.

**Comment by PG85** [comment]
Hey @AyumuTheDreamer, thanks for reporting this. Haven't tested this for a while, may be because of custom biomes being used that don't replace to a vanilla biome, which would mean the biomes would be absent from the registry and the world won't work. Please ask on the OTG Discord as well, people there may be able to help you more quickly.

**Comment by lukastrkan** [comment]
> Title is self explanatory. Every time after i uninstalled the mod i crash, but reinstalling it fixes it. i just want a superflat/biomes o'plenty world.

You mean OTG mod, right? 
If yes, then #197

**Comment by PG85** [comment]
Ah ok, so removing OTG-Core fixed it?

**Comment by AyumuTheDreamer** [comment]
Oh! I fixed it by removing the folder called 1.12.2.

**Comment by PG85** [comment]
Ok, glad it's fixed, thanks for reporting :).
