### ISSUE TITLE
[Feature] Void Fog and Visual Effects

### ISSUE THREAD

**Issue by ghost** [PG85/OpenTerrainGenerator#31]
i think it would be a great visual addition to gameplay if it would be possible to add (audio?-)visual effects to biomes. the effects could be activated in biome x or in biome y but only when below height level a or above b, at time xyz, etc. most importantly the void fog that got removed a few updates ago, should be added again with this feature - the first thing i'm going to do is add it on altitude 1-8 for every biome :D . there could be effects for making the players vision blurry (when they are in a poisonous biome or above height 300) or very bright (when they are very high up at daytime) or colour effects, or something else.

**Comment by PG85** [comment]
Hey Kevin,

That sounds really cool but is not within the scope of this mod. With the latest commits for 1.10.2 and 1.11.2 I have added some settings for custom dimensions like game rules and world provider settings (fog/sky settings, water vaporises, sleeping allowed, respawning allowed etc) so that players can make dimensions similar to the nether and end but that's about as far as we'll go in that direction. Adding audio effects and whole new fog effects will have to be done using a different mod.

**Comment by ghost** [comment]
@PG85 fair enough. 

>I have added some settings for custom dimensions like game rules and world provider settings (fog/sky settings, water vaporises, sleeping allowed, respawning allowed etc)

nice i was really hoping for that.  having fog/sky should be good enough :D 

btw, this isn't really related to this issue, but since you already brought up world settings - do you plan to include biome specific bedrock settings to the mod? i've been playing around with custom presets in vanilla minecraft lately and i made some fantastic flying islands with nice wide lands and cave systems under and above water. and while i was playing around with that i had an idea. what if it was possible to have bedrock under some biomes, and none under some others where it fits better to just have a flying island. i think the options for the biomes regarding bedrock should be like this

top: none/flat/natural

bottom: none/flat/natural

and then there should be some setting that affects how the cutoff of bedrock between a biome with bedrock and one without should happen. like a "1" could be just a cut off right at the border, while a "0.7 could be a lot smoother, with the (in case of a biome with natural bottom bedrock meeting one with no bottom bedrock) bedrock fading out and being visible from above to give the world a torn apart and broken feeling instead of just cutting off the sky islands from the ground.

maybe i could try to explain it more in-depth in a seperate issue if you want.

**Comment by PG85** [comment]
Well, you can already remove the bedrock or make it flat via the worldconfig, to make it different for each biome you could remove bedrock entirely and create a custom bedrock layer using some of the biome settings like customheightcontrol. For the rest I'm afraid that because the idea is not an essential feature it will have to go on to the "to-do" heap for now, which unfortunately is quite large already :o

**Comment by ghost** [comment]
@PG85 i see, i wonder if it's possible to create a dynamic thinning out effect of the bedrock when going from normal terrain to skylands, just by using the current biome settings. if not i guess just cutting it off and then placing random bedrock structures on the bottom would create a similar effect.

>I'm afraid that [...] will have to go on to the "to-do" heap for now, which unfortunately is quite large already

what do you mean with unfortunately :D
