### ISSUE TITLE
Issues with the Ruins mod

### ISSUE THREAD

**Issue by mensreaMC** [PG85/OpenTerrainGenerator#329]
OTG Mod for Forge
1.12.2_v8_r6
Forge: 14.23.5.2846

Latest version of the Ruins mod (there's no version numbers).

Ruins often spawn with trees, grass, and especially sunflowers all over them. I took some pictures for this thread: https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/269

Since I made that post I'm no longer finding the bald spots, probably some change that was made in a recent version of OTG. Still getting the flowers and trees in things, though. 

Was hoping that something could be done from OTG's end to make these mods play nice since the Ruins guy said he doesn't have time for it.

**Comment by mensreaMC** [comment]
Looks like the ruins guy is also saying that this is the reason ruins clip in to each other and spawn too close together as well. I posted some example pictures in the thread on the Ruins github.

**Comment by mensreaMC** [comment]
Ruins mod structures spawn after objects but before trees in the OTG spawn order.

**Comment by PG85** [comment]
Hey @mensreaMC , thanks for figuring this out! Spawning plants and trees on top of things is intentional behaviour and used by OTG preset devs to layer objects/resources on top of each other. OTG would have to detect other mods' structures and cancel resource spawning (plants etc) in that location. That's currently a more trouble to get working/looking right than it's worth, unless more people complain about it I don't think it'll be worth the time. If you can find instances of this issue that are game-breaking and affect a lot of players, feel free to reopen this issue.
