### ISSUE TITLE
Server output/console spam "Compressing structure-cache and pre-generator data"

### ISSUE THREAD

**Issue by MxtressMyxx** [PG85/OpenTerrainGenerator#401]
"Compressing structure-cache and pre-generator data" is spammed so hard on my server I cannot read any other output.

1. Is there a way to disable this message
2. Why is it spamming the console so hard?
3. What other info can I provide to be more helpful?

**Comment by tulir** [comment]
I have the same problem after pregenerating with a radius of 200 (160000 chunks). OTG v8.3, Biome Bundle v6.1, Forge 14.23.5.2847.

After the "Compressing structure-cache and pre-generator data" line, it says "Removed 0 cached chunks"

The 7th value in `Biome Bundle/OpenTerrainGenerator/PregeneratedChunks.txt` seems to be increasing rapidly (approx. 1k/second, currently mine is around 10.4 million) , maybe related to this

**Comment by tulir** [comment]
I found a way to hide the message from logs: set `LogLevel: Quiet` in `mods/OpenTerrainGenerator/OTG.ini`. The source of the log spam doesn't seem to cause any other negative effects like high CPU usage, so just hiding the logs is probably good enough.

**Comment by PG85** [comment]
Hey @AnsuzThurisaz , thanks for reporting this. Not sure why it would do that, can you see anything else happening at the same time, like the server saving? If this keeps happening, you can send me your world if that's manageable.

**Comment by LST-Staardust** [comment]
Hello @PG85 , i have same issue right now, i loaded 100 chunks and since then the console wont stop spaming "Compressing structure cache and pre generator data" and "Removed 0 cached chunks"

As you asked, the server isn't saving anything, i could try to send you the world but it's on a modpack i have made personally so idk if this would work

**Comment by csweet89** [comment]
I also have this issue, I tried to pre-gen 10 chunks as a test and its spamming me hard now.

**Comment by csweet89** [comment]
I resolved the issue by deleting all the files except "config.yaml" from "Minecraft\Biome Bundle\OpenTerrainGenerator"

**Comment by LST-Staardust** [comment]
@csweet89 does this delete anything or break the generation or something ?

**Comment by tulir** [comment]
Just deleting `PregeneratedChunks.txt` seems to be enough (the file with the rapidly increasing value I mentioned). The file was automatically recreated with some default values and nothing seems broken

**Comment by LST-Staardust** [comment]
I can confirm this works, i'll check if there's any problem with the map/generation and if there's one i'll comment again. Thanks btw.

**Comment by PG85** [comment]
Hey guys, deleting the config.yaml or PregeneratedChunks.txt may cause issues with the pregenerator and BO4 structure generation (which you're likely not using), so ofcourse isn't prefered. I have not been able to reproduce this, so wonder if this only occurs with certain modpacks. To anyone that has this problem:

- Is it reproducible every time you create a new world and pregenerate?
- If so, does it still happen when not using other mods (only OTG)?
- If so, can you figure out which mod combination is causing the problem?

**Comment by PG85** [comment]
Hey guys, you should be able to fix this by editing the Pregenerator.txt (if I recall the filename correctly). The problem is that the total number of spawned chunk is 1 lower than the expected total on finishing pregen. I've added a few fixes that may solve the issue for v9, not entirely sure what caused it though (may have been a race condition), so if you still see the issue, feel free to reopen this ticket or create a new one.

Pregenerator.txt is a text file in the world save/OpenTerrainGenerator folder. It contains a number of comma-separated values. The first value is a number, this indicates the amount of chunks spawned.
- Figure out if the number is 1 lower than the total amount of chunks you expect to generate with the current radius. Note that radius 0 is disabled, radius 1 is 1 chunk. 
So 
- 1 chunk total for radius 1
- 9 chunks total for radius 2
- 25 chunks for radius 3, etc.

If your spawned is 1 lower than the total, then manually add 1 and save the file. The log spam should stop.

If you still see this issue with v9, feel free to reopen this ticket or create a new one.
