### ISSUE TITLE
There seems to be an issue between this mod and Gravestone-Extended

### ISSUE THREAD

**Issue by RodrigoTaipe93** [PG85/OpenTerrainGenerator#410]
Basically is the following:

- Error, minecraft engine attempted to populate two chunks at once

- https://paste.ee/p/2L1nI
- https://paste.ee/p/kmmtT

**Comment by PG85** [comment]
Hey @RodrigoTaipe93 , thanks for reporting this. The "Error, minecraft engine attempted to populate two chunks at once" is a warning that shouldn't cause a crash, although can lead to artifacts in terrain generation. It's most likely caused by other mods spawning things in unloaded chunks, which they should'nt do, since it can cause major lag spikes (its called cascading chunk generation).

In order to find out which mod is causing the problem, you can try either removing mods and seeing when the issue disappears, or setting the log level to Trace in mods/OpenTerrainGenerator/OTG.ini file for a stack trace, the stack trace should include the mods making the calls to generate the chunks.

**Comment by PG85** [comment]
OTG should not be causing this, it's likely another mod spawning objects / requesting blocks in unloaded chunks. Please try to track down which mod it is (exclude every other mod if possible) and file a bug report with the mod's owner, thanks!
