### ISSUE TITLE
I Load the world and a few moments later it crashes- R.A.D Modpack

### ISSUE THREAD

**Issue by Lyted21** [PG85/OpenTerrainGenerator#413]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x ] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [x ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Description
I just load the world and then it crashes. The crash report: https://paste.dimdev.org/eqozeruqil.mccrash

**Comment by PG85** [comment]
Hey @Lyted21 , thanks for reporting this. When did this start happening? When creating a new world or joining an existing one? Did you make any changes to the world in between sessions? Can you reproduce this?

**Comment by Lyted21** [comment]
it started when i put down a reforging station i think, because after that it crashed, so i updated the mod to the lastest version, and it stills crashes whenever i try to re-enter the world but it runs normally when i create i new one

**Comment by PG85** [comment]
Unfortunately I can't reproduce this, so I can't debug it. The version of OTG you're using is also a bit old, the code has changed since then, so the problem may have been fixed already. It appears to be related to the pregenerator though. You can try deleting saves/worldname/openterraingenerator/PregeneratedChunks.txt (backup your world first). If you get it working, I suggest you update to the newest version of OTG. I can't guarantee that this will work and that the problem won't come back later when pregenerating or exploring. If you find a way to reproduce the problem with a new world, let me know and I'll take a look. Thanks and good luck!
