### ISSUE TITLE
The problem of world management module in sponge

### ISSUE THREAD

**Issue by SakuraWuhen** [PG85/OpenTerrainGenerator#415]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [x] 1.12.2_v8.3
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
[The full Spigot Server or Forge versions that you are running]
1.12.2-forge1.12.2-14.23.5.2838
spongeforge-1.12.2-2838-7.1.7-RC3909

#### Server/Client Log
[The full latest.log file from your server or game client, especially important if you have a stack trace]
In the description below
#### What other plugins are you running?
I tested in the environment without plugins and mods and still have this problem
--
#### Description
I am a player from China, please forgive me for using machine translated English to communicate with you
The problem originated from the 1.12 sponge server. We are using OTG with sponge to create our fantasy world.

#### Error 1: The World Management Module (RFTools) generates a crash in the Sponge side
Use the O key to generate a preset world Skylands in the sponge, and use the teleport button to transfer to this world. The character cannot move. The surrounding scene can only load a small part. After tens of seconds, it collapses and outputs this error report
[Generate World Error.txt] (https://github.com/PG85/OpenTerrainGenerator/files/4058929/Generate.World.Error.txt)
** (This is the case with any preset, creating the world will always go wrong) **

#### Error 2: Unable to load maps other than the main world
The new world generated by any non-RFTools method, this error must occur after restarting the server and then entering the server (such as the world generation instruction / world create of the multi-world plugin)
[Multi-world loading error.txt] (https://github.com/PG85/OpenTerrainGenerator/files/4058917/Multi-world.loading.error.txt)
It is very important for the server to load multiple worlds at the same time. We often need to load a lot of small games / RPG / building maps in order to work, but because the new world generated with RFTools will crash, which makes us unable to load Extra world

#### Error 3: Errors generated by v6 version world
To load the map in the world, I tried the OTG V6 version without the World Management Module (RFTools)
When using the multiworld plugin's world generation command / world create to generate a new world, the following error occurs:
java.lang.NoSuchMethodError: net.minecraft.world.WorldSettings.func_77166_b () Lnet / minecraft / world / WorldSettings;
    com.pg85.otg.forge.dimensions.WorldProviderOTG.func_76572_b (WorldProviderOTG.java:87)
    Com.pg85.otg.forge.OTGWorldType.getBiomeProvider (OTGWorldType.java:70)
    Net.minecraft.world.WorldProvider.func_76558_a (netProvider.java:40)
    At net.minecraft.world.WorldServer. <init> (WorldServer.java:116)
    At net.minecraft.server.MinecraftServer.func_71247_a (MinecraftServer.java:298)
    At net.minecraft.server.
    private.DedicatedServer.func_71197_b (DedicatedServer.java:270) on net.minecraft.server.MinecraftServer.run (MinecraftServer.java:486)
    In java.lang.Thread.run (unknown source)

After generating the world, enter the transmission instruction to go to the world. This error will still be returned. It seems that it is caused by OTG trying to access the client-only method from the server.

**I have been using OTG with Sponge to run the server since 1.10.2. OTG 1.10 does not cause the above problems and can be compatible with the world created by plugins.**
-
The inability to create a multi-world problem prevented our creative work on the server from continuing. I felt very helpless, so I came here to find a solution. When I browsed the error report, I saw a response under this question: 
https://github.com/PG85/OpenTerrainGenerator/issues/348
I learned that OTG does not support sponge. I want to know the reason why sponge is not supported. In the more than one year that the sponge server has been running, the only exception that has occurred is caused by the world management module.

In the end, OTG is the best world generator I have ever seen, and it is our only choice. Only it can help us realize our fantasy and create the world we yearn for. Thank you for your great work.

**Comment by PG85** [comment]
Hi @SakuraWuhen , thank you for your message. Sponge is not officially supported because we don't have the time to properly test and develop it. OTG is made to work with Forge and Spigot, so if Sponge doesn't do anything differently, OTG should work. I have not tested with Sponge recently, but the latest versions of OTG (v8 and higher) did fix a lot of problems, which may also have affected Sponge.

Separately from any Sponge issues you may have, OTG's dimension features are known to cause some problems with other dimension mods, such as RFTools. This is something we intend to improve in the future. I have not tested what is possible and not possible with RFTools at the moment, but I hope that you may be able to combine OTG's dimension features with RFTools'. I do know that it will not work if other mods try to create OTG dimension, OTG needs to manage its own dimensions. If other mods teleport players to OTG dimensions, there may also be some bugs. Otherwise, if other mods don't touch OTG's dimensions, there is a good chance they should be able to work together (OTG also does not touch other mod's dimensions). Unfortunately I did have to make some changes to the minecraft code that might interfere with other dimension mods trying to modify the same code. I still have to look at all the other dimension mods available, see how they are doing things, and make sure OTG doesn't interfere with them. As I said, this is something planned for the future, I hope you can use the current features to create a world for now. Thanks for using OTG!

**Comment by PG85** [comment]
Even though it may be difficult to communicate in English, please join us on our Discord server at https://discord.gg/UXzdVTH. There are many more users like you there, trying to get all kinds of worlds working, they can tell you about the possibilities of OTG with other mods.

**Comment by SakuraWuhen** [comment]
Thank you for your careful reply and suggestions to me. I tried to create a world with RFTools. It can coexist with the world of OTG without error. This good news makes us very happy.
Thank you also for your invitation, but you may know that China has a network wall. I need to buy an expensive VPN to log in to Discord, which is more troublesome than a language barrier. But the next time I run into problems, I will find a way to go to Discord for help
Mr. pg85, sincerely hope you have a happy life :)

**Comment by PG85** [comment]
Thanks for your message, I'm glad to hear you got it working! Hope you have fun with OTG :)
