### ISSUE TITLE
OTG "O" menu crashes with ExtraPlanets.

### ISSUE THREAD

**Issue by Elim1nator** [PG85/OpenTerrainGenerator#446]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [X ] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [X ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
[forge-1.12.2-14.23.5.2847.jar ]

#### Server/Client Log
[https://pastebin.com/rdgpJEXe]

#### What other plugins are you running?
[Biome Bundle, MJRLegendsLib-1.12.2-1.1.9, GalacticraftCore, Galacticraft-Planets-1.12.2-4.0.2.244, ExtraPlanets-1.12.2-0.6.2]

#### Description
[With both OTG and ExtraPlanets-1.12.2-0.6.2 added, when you make a Biome Bundle world in the 'O' menu it crashes]

[The world should create and be accesable]

Crash report: https://paste.dimdev.org/gilikidedo.mccrash

**Comment by PG85** [comment]
Hey @Elim1nator , thanks for the feedback. Will take a look at this for 1.12.2 v9_r10.

**Comment by PG85** [comment]
I had to change the keybinding for the O menu since Galacticraft uses O as well. After that, seems to work fine with the newest dev build. Please try this, rename .zip to .jar.
[OpenTerrainGenerator-1.12.2 - v9.0_r11.zip](https://github.com/PG85/OpenTerrainGenerator/files/5176965/OpenTerrainGenerator-1.12.2.-.v9.0_r11.zip)

If you're still seeing problems, feel free to reopen this issue, thanks!
