### ISSUE TITLE
Border biomes are inconsistent, meaning it's impossible to stop climate zones from clashing

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#449]
This has annoyed me forever so I thought I'd do some testing and post an issue for it.

The below is a simple world of just 4 biomes, with two normal biomes and two borders. The green circled area is what should happen consistently, while the red circled areas are where the borders do not draw consistently and so cause biomes that are not supposed to be adjacent to be so.

![OTG Border Test](https://user-images.githubusercontent.com/9453952/77545782-daa19000-6ea2-11ea-89bd-48d7eefac1b1.png)

**Comment by MCPitman** [comment]
[BiomeLayoutTest.zip](https://github.com/PG85/OpenTerrainGenerator/files/4381921/BiomeLayoutTest.zip)

Here is the test world I used to create the /otg map output above, it's a simple world with only 2 main biomes and 2 border biomes.

**Comment by Darsenia** [comment]
Oh that issue is a bad thing.Sometimes I had to make at least 2 border biomes to be sure that the center will not meet surrounding biomes( and it still happenes sometimes).It is also the main problem in making biomes with higher/lower water level,for example.
I've noticed,that it happenes more often in places,where the one biome with bigger border meets other biome with smaller border,and it makes a smaller border to dissapear.The main biome in such places is more protruded,and the size of this protrusion is too small to form a normal border.Bigger border could help a bit,but it not always intended to be bigger...Also a bit similar thing happenes to an isle biome.If the main biome is too protruded and the isle is big enough,it could not form the isle at all on this "tail".Mesa-like biomes are good example.

**Comment by PG85** [comment]
Fixed by @SuperCoder7979 for v9_r9! :D
