### ISSUE TITLE
Conflict between Fossil mod and OTG

### ISSUE THREAD

**Issue by RodrigoTaipe93** [PG85/OpenTerrainGenerator#460]
There seems to be an issue regarding ID's. The other author pointed out to OTG for the fix :(

- https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/issues/1714#issuecomment-608565894

**Comment by PG85** [comment]
Hey @RodrigoTaipe93  , OTG has been using dynamic biome id's for new worlds since OTG 1.12.2 v8. The only problems you might have is when you add/delete biome mods after world creation, which would affect the biome registry. If you have any problems or need help updating a legacy world, join us on the otg discord at https://discord.gg/UXzdVTH, thanks!
