### ISSUE TITLE
Modpack Crash!

### ISSUE THREAD

**Issue by Xsellment** [PG85/OpenTerrainGenerator#480]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x ] OTG Mod for Forge 
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]

1.12.2_v8.3

#### Forge or Spigot Versions

Roguelike latest 1.12.2 version https://pastebin.com/raw/9VMHzFvN
#### Server/Client Log
https://controlc.com/14497f94

No forge or Opti fine installed https://pastebin.com/raw/9VMHzFvN
#### Description
[What is happening? - Explain what happens and what steps should be done to reproduce the issue. Ideally with pictures;)] 
I logged in one day with this issue after clicking "Play"
https://prnt.sc/suv0g7 (I clicked the "Get Link" button, it doesn't work trust me.
[What did you expect to happen? - Explain what you expected to happen after performing the previously described steps]
I use Tlauncher. I clicked "Enter the game" from the launcher, loads up like normal. I select my world and press play, I'm presented with the picture above.
****For some reason forgilin is outdated in the mudpack, is that weird?

Can you provide a Minimal, Reproducible Example? 
See here for details: It's a crash error, that's it.

**Comment by BiomeBundle** [comment]
This happens because there's a biome ID conflict in the world. It can either be because a mod was added or updated to add a new biome - or, it could be that the world was created with v6 OTG which "allowed" biome ID conflicts to happen (but caused issues), whereas v8 OTG doesn't allow this. New worlds created with v8 will work fine.

You can either wait until v9 is stable (which will allow conflicts again), start a new world with v8 or downgrade OTG to v6.

**Comment by Gunner76th** [comment]
@BiomeBundle Please be advised that the user issuing the bug report is using a modified version of the RAD Modpack by Dreams0. The user issuing this report has modified the modpack without consulting the modpack creator, or his support staff (such as myself). Additionally is using the illegal launcher TLauncher. We would have addressed this issue internally on our discord, however because they are using TLauncher we do not provide support when an illegal launcher is being used.

**Comment by Xsellment** [comment]
> This happens because there's a biome ID conflict in the world. It can either be because a mod was added or updated to add a new biome - or, it could be that the world was created with v6 OTG which "allowed" biome ID conflicts to happen (but caused issues), whereas v8 OTG doesn't allow this. New worlds created with v8 will work fine.
> You can either wait until v9 is stable (which will allow conflicts again), start a new world with v8 or downgrade OTG to v6.

Thank you!

**Comment by PG85** [comment]
Thanks for reporting @Gunner76th  and @Xsellment! I'll close this issue for now.
