### ISSUE TITLE
Crash from OTG Mod

### ISSUE THREAD

**Issue by evielarson2** [PG85/OpenTerrainGenerator#483]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] Other - 1.12.2-v8.3

#### Forge or Spigot Versions
forge-14.23.5.2847

#### Server/Client Log
[crash-2020-06-10_16.56.07-client.txt](https://github.com/PG85/OpenTerrainGenerator/files/4759365/crash-2020-06-10_16.56.07-client.txt)
(for some reason I couldn't open the crash report in my browser...)

#### What other plugins are you running?
I'm using the Curse Engineer's Life modpack for 1.12.2.

#### Description
My world keeps crashing every time I want to turn it on, and OTG seems to be the problem...

![crash](https://user-images.githubusercontent.com/66738051/84283544-68ecf000-ab3b-11ea-8834-f83d339717c2.PNG)

**Comment by authvin** [comment]
From a glance, this seems to be related to this issue: https://github.com/PG85/OpenTerrainGenerator/issues/445

**Comment by PG85** [comment]
Hey @evielarson2 , looks like some of the .txt files were corrupted, presumably because of a crash or abnormal exit during saving. 

For OTG 1.12.2 v0.0_r10 I've made OTG rename existing txt/yaml files to xxx-backup before writing new files. If during loading a file is corrupted, it'll try to load the backup file. When reading/writing fails, OTG logs an error telling the user how to manually fix the problem (where possible). r10 will be available on the OTG discord a.s.a.p.

For help fixing your existing world, please ask on the OTG Discord. You should be able to create a new world with the same setup and copy the files to your old world (BiomeId's.txt, Config.yaml, DImensions.txt, WorldSave.txt).
