### ISSUE TITLE
OTG Crash

### ISSUE THREAD

**Issue by SMHerobrine** [PG85/OpenTerrainGenerator#487]
#### OTG Plugin or Mod

- [ x ] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version

- [ x ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions

forge-14.23.5.2854 (minecraft 1.12.2)

#### Server/Client Log

Crash log by VanillaTweaks: https://justpaste.it/8va20

#### What other plugins are you running?

https://sm-master-wikis-beta.fandom.com/wiki/Temp

#### Description

I was testing if OTG and BBOP were working in my modpack but it crashed in a whew minutes.

**Comment by PG85** [comment]
Hey @SMHerobrine , this appears to be cascading chunk population caused by other mods / a combination of mods. Please try removing mods to narrow down which mods are causing the issue, then I can take a look at fixing it. You can also try using the latest dev version of OTG, available on the discord at https://discord.gg/UXzdVTH. Thanks!
