### ISSUE TITLE
OTG infinitely Compressing structure-cache and pre-generator data

### ISSUE THREAD

**Issue by BlueYoshi68** [PG85/OpenTerrainGenerator#489]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x ] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
[The full Spigot Server or Forge versions that you are running]
forge-1.12.2-14.23.5.2846
#### What other plugins are you running?
[List of your Mods or Plugins installed, ideally with versions]
145 mods, I can't really list them all.
#### Description
[What is happening? - Explain what happens and what steps should be done to reproduce the issue. Ideally with pictures;)]
Just pregenerating a world with the Biome Bundle O plenty addon and it just spams
02.07 03:02:11 [Server] Server thread/INFO [OTG]: Compressing structure-cache and pre-generator data
02.07 03:02:11 [Server] Server thread/INFO [OTG]: Removed 0 cached chunks

[What did you expect to happen? - Explain what you expected to happen after performing the previously described steps]
This not to happen.

**Comment by PG85** [comment]
Hey @BlueYoshi68 , this should be fixed with the latest dev version of OTG, available on the Discord at https://discord.gg/UXzdVTH. You may need to fix your pregenerator.txt by editing it to make sure that the amount of chunks pregenerated is at 100%, although OTG should attempt to fix this automatically. If you're having problems, give us a holler on the discord, thanks!
