### ISSUE TITLE
Null pointer crash when pre-generated block

### ISSUE THREAD

**Issue by SakuraWuhen** [PG85/OpenTerrainGenerator#516]
#### OTG Plugin or Mod
- [X] OTG Mod for Forge

#### OTG Version
This error has occurred in V9_9 and still exists when upgrading to V9_10

#### Forge or Spigot Versions
forge-1.12.2-14.23.5.2838

#### Server/Client Log
[crash-2020-09-04_21.11.02-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/5175014/crash-2020-09-04_21.11.02-server.txt)
[latest.log](https://github.com/PG85/OpenTerrainGenerator/files/5175026/latest.log)

#### What other plugins are you running?
I have tested with OTG only

#### Description
I’m using OTG’s world management system to pre-generate the 400 blocks preset by "TravelersDreamCompact"
Encountered this error during the build process, and every time the server is started it will crash due to it

If you need more tests and information, please let me know
and thank you。

**Comment by PG85** [comment]
Hey @SakuraWuhen, I suspect this is due to a plant resource using a block type that isn't known, but I can't be sure just from the crash report. Please try this, it has some fixes for blocks/materials: 
[OpenTerrainGenerator-1.12.2 - v9.0_r11.zip](https://github.com/PG85/OpenTerrainGenerator/files/5176941/OpenTerrainGenerator-1.12.2.-.v9.0_r11.zip)

Rename .zip to .jar. If you're still having problems, feel free to reopen this issue. Thanks!
