### ISSUE TITLE
Using otg with jeid will not generate worlds and crashes in already generated worlds.

### ISSUE THREAD

**Issue by ghost** [PG85/OpenTerrainGenerator#582]
I'm trying to make a 1.12.2 modback using forge-14.23.5.2854 with open terrain generator v9.0 and JustEnoughIDs 1.0.3-55 and when I open otg worlds the game crashes with the message "The game crashed whilst exception in server tick loop
Error: java.lang.RuntimeException: Error: Biome "Dregora_RFDirtPuddles" has an id between 0-255 but uses replaceToBiomeName. Virtual biomes must have id's above 255, please check your WorldConfig's custom biomes setting.
Exit Code: -1"

[crash-2020-12-04_17.36.09-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/5643756/crash-2020-12-04_17.36.09-server.txt)

Also when trying to generate an otg world it comes up with a message "Error    Not enough biome id's aviable to add all dimensions."

The same problem occures with NotEnoughIDs and both Jeid and Neid installed at the same time.

If anybody knows how to fix this, any and all help would be appreciated!

**Comment by authvin** [comment]
JEID and NEID don't interact with OTG at all. Your crash with Dregora will be solved if you remove the CustomBiomes: setting from the worldconfig

**Comment by ghost** [comment]
> JEID and NEID don't interact with OTG at all. Your crash with Dregora will be solved if you remove the CustomBiomes: setting from the worldconfig

How do I delete  CustomBiomes from worldconfig, since I was unable to fix it?

Also thought that it would be an incompatibility problem, since some other people have had this problem and it happens with Biome Bundle and Biome Bundle O Plenty too.

**Comment by authvin** [comment]
You open the worldconfig file of your given preset in a text editor, then remove the CustomBiomes entry

**Comment by ghost** [comment]
This doesn't fix the issue.
The game still crashes while opening old worlds and while generating worlds still gives the same error.

**Comment by PG85** [comment]
Hey @Nyypa , for questions like these, please join us on the Discord at https://discord.gg/UXzdVTH. 

For "Error: Biome "Dregora_RFDirtPuddles" has an id between 0-255 but uses replaceToBiomeName" it looks like either your Dregora preset has an error in it or has been corrupted. NLBlackEagle (creator of Dregora) is also on the Discord.

In terms of "Error Not enough biome id's available to add all dimensions", OTG has a maximum of 256 custom biomes globally that can be registered (regardless of JEID), and a max of 1024 virtual biomes per dimension (virtual biomes are biomes that use ReplaceToBiomeName, and don't have their own registered id). Adding BB, BBOP and Dregora can cause you to exceed that limit. BB/BBOP/Dregora would have to change some of their custom biomes to virtual biomes in order to fix this. For 1.16, the biome id limit will not be an issue anymore.

Please join us on Discord for more questions, thanks!
