### ISSUE TITLE
Possible Bug with world generation

### ISSUE THREAD

**Issue by Graagh** [PG85/OpenTerrainGenerator#63]
Using Terrain-Normal and BiomeMode=Normal in a world default-generated with an empty WorldConfig.ini, I adjusted the WorldHeightScaleBits from 7 to 8.  Then I adjusted the individual biome config files to compensate for the increased height.  The comments are absolutely no help, and are obviously false, but I also noticed that using a BiomeHeight=-2.0 causes the biome to generate empty, with only bedrock and the world water level  Any other value (within the possible range) seems to work fine,  Setting the value too low, like -5.0 (which is what the comments suggest should be correct) demonstrates the same behavior.

In reference to the comments, 0.0 does indeed seem to represent half the world height (going from 64 at 7 bits to 128 at 8 bits), but the world water level doesn't behave as indicated.  It should go from height 64 = 0.0 for 7 bits, to height 64 = -5.0 for 8 bits, assuming height range from -10.0 to 10.0 as documented.  Instead 8 bits for scale seems to put height 64 at -2.0.  I can confirm that every 1.0 of height seems to represent 32 blocks in-world.  So a 256-height world would have 8 divisions, and thus range from -4.0 to 4.0.  This is consistent with y=64 at -2.0 as mentioned above.  Docs need serious attention.

**Comment by MCPitman** [comment]
The documentation in these files has been the same for years and is fine. I'm not sure why you would say they aren't. There is more documentation that just the comments in the files if you bother to look:

http://openterraingen.wikia.com/wiki/Open_Terrain_Generator_Wiki

**Comment by Graagh** [comment]
Well, not to be obnoxious or anything, but "if I bother to look" what I see is:
Making your own custom world generator from scratch (Coming Soon)
and
WorldConfig.ini, with the same text as the comments.
This doesn't exactly shed any additional light on the subject.

Would you perhaps care to address any of my specific point directly?  I'm honestly struggling here, because the behavior I'm seeing doesn't line up with the comments.  Perhaps I AM an idiot, as you obviously believe by your tone, but your condescending replies aren't helping to make me any smarter.

Anyway, I'll do some more detailed testing and see if I can disprove the problem, or provide some more detailed examples.

**Comment by MCPitman** [comment]
It is not the same text as the comments, there is additional information that addresses some of what you have mentioned, such as: https://vignette.wikia.nocookie.net/terraincontrol/images/e/ef/KSBs2uu.png

No offense but I don't think you are in any position to talk about tone when your 'issues' are full of invalid criticisms and claims of the documentation being 'obviously false' when you yourself admit to not testing thoroughly in the first place.

Do you think world presets such as [Biome Bundle](https://minecraft.curseforge.com/projects/biome-bundle), [Skylands ](https://minecraft.curseforge.com/projects/otg-skylands )or [Flatlands ](https://minecraft.curseforge.com/projects/otg-flatlands) were made possible because OTG does not work? Perhaps do more than a few minutes experimentation instead of wasting everyone's time posting non-issues here. 

This is a bug tracker not a discussion forum, you are welcome to ask questions etc over at www.reddit.com/r/openterraingen or join the Discord channel at https://discord.gg/UXzdVTH

**Comment by Graagh** [comment]
Some valid points.  My apologies for those.

I don't assume OTG doesn't work.  I assume, from the fact that this is a bug tracker, and recent, fairly major bugs have been posted about BiomeMode: Normal, that there might be bugs in it.  I don't think that's an unreasonable assumption.  I further assumed that, most likely, people making their own worlds started with BiomeBundle and made their modifications and customizations from there - which does not use BiomeMode:Normal.  And therefore, that the Normal setting might not be as thoroughly tested as BeforeGroups.

As for the documentation, this is from one of the default biome config files:

 BiomeHeight mean how much height will be added in terrain generation
 It is double value from -10.0 to 10.0
 Value 0.0 equivalent half of map height with all other default settings

The table you posted from the wiki (thank you very much, by the way, that helps loads) clearly shows the value range from -4.0 to 4.0, as well as the known error at -2.0.  The documentation in the comments is obviously false, and my criticism is not invalid.  Whether or not you consider documentation issues to be a bug is up to you.
