### ISSUE TITLE
1.16 - RandomBlock() not working in bo3s

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#653]

**Comment by PG85** [comment]
I put a breakpoint on randomblock's setBlock call and fired up BB. Breakpoint is hit, appears to be placing blocks. Problem may have been due to underlying issues, or a specific combination of settings. Tested with 0.0.14, please reopen this issue if the problem isn't fixed, and provide preset/biome/bo names so I can check it out, thanks!
