### ISSUE TITLE
1.16 - A couple Tree() options

### ISSUE THREAD

**Issue by WACriminalG2** [PG85/OpenTerrainGenerator#656]
#### Is your feature request related to a problem? Please describe.
Not necessarily a "problem", more a pair of use case frustrations that might be solved together. 

1. For cave worlds, generating even vanilla trees requires you to provide a BO3 for them -- multiple BO3s, if you want varying sizes and such.
2. Including any modded trees requires BO3s regardless of whether you're doing a cave world or not.

#### Describe the solution you'd like
1. An optional boolean parameter on the Tree() resource function, OverrideLightCheck, that forces the game to ignore light levels and sky access when spawning trees. Obviously pack devs will need to be careful about how they use this, but it would be handy.
2. There was a mod in 1.12.2, Tree Tweaker: https://github.com/superfluke/treetweaker/wiki . It's a CraftTweaker addon that allows pack devs to generate new trees using common shapes, such as "oak" and "canopy", then defining the log and leaf blocks for said tree. It would be cool if we had a tool to generate trees in this manner -- either an external tool that generates BO3s, or an inline function within OTG that creates and registers them.

#### Describe alternatives you've considered
Going outside and looking at real trees.

#### Description aka Additional context
This is definitely something for the backlog, if not the garbage can.

**Comment by PG85** [comment]
Thanks for reporting this. For vanila trees we use mc logic, so we just tell mc we want a tree somewhere and it does the rest. So changing spawn requirements for vanilla trees would require a custom implementation of them, which in a sense is what we've done with BO's, except they're more free-form/roll-your-own. Love the idea of a tree generator, I think that's outside of the scope of OTG though, especially since you can achieve similar results already with BO's. Ideas are always welcome though :).
