### ISSUE TITLE
Bug: Player spawning underground on spigot 1.16.5

### ISSUE THREAD

**Issue by AzureAqua** [PG85/OpenTerrainGenerator#660]
#### OTG Plugin or Mod
- [x] OTG Plugin for Spigot

#### OTG Version
- [x] Other - 1.16.5-0.0.11

#### Forge or Spigot Versions
paper-1.16.5-714.jar

#### What other plugins are you running?
![plugins](https://user-images.githubusercontent.com/41600194/120630597-e69dc000-c45e-11eb-93b1-e4718e1a99a7.png)

#### Description
The player does not always spawn on the surface when spawning in a height modified biome. This only happens on spigot and works fine on forge

**Comment by authvin** [comment]
This is caused by vanilla spawn detection not working well with OTG biomes, have a fix in mind for it. What happens is, when it fails to find a valid spawn point, it chooses a point at random. Spigot then finds the nearest Safe location, which can be underground. You can see the same with Forge when players spawn in the ground under the surface.

This should not happen in biomes with grass surface blocks right now

**Comment by FrankTCA** [comment]
Fixed! Will be out in next release =)
