### ISSUE TITLE
Add support for using blocks with NBT data as surface, ground and stone block.

### ISSUE THREAD

**Issue by I-am-mimic** [PG85/OpenTerrainGenerator#664]
So I've had an idea for a biome I want to make. Requiring that the surface, stone and ground blocks use blocks from chisels and bits. Since Chisels & Bits blocks are entirely custom made by the user, it requires the use of NBT data. I need a specific floor pattern so I can't depend on setting up different blocks in CH&GC and expect it to look even. I can't use Image mode because I want this to be procedurally generated. With Chisels & Bits I can create a custom pattern inside a single block. Allowing it to be used as a tile-able pattern for world gen, while keeping its intended pattern design. Unfortunately NBT blocks can't be used outside of BO3's & BO4's. 

I would accomplish this by using a similar method to how BO3's and BO4's handle NBT data blocks. So maybe a command could be implemented to get the block ID, Block state and NBT, and have it copy the data to the users clipboard. Or you could have them specify the BC file and have it place it in the desired spot.

**Comment by SXRWahrheit** [comment]
Blockstates are already supported.

**Comment by authvin** [comment]
This is not asking for block states, but NBT

**Comment by SXRWahrheit** [comment]
This will have to be a backlog for post-1.0, and it may require enabling a config entry to prevent accidental performance impacts.

**Comment by PG85** [comment]
Surface/ground/stoneblock are placed during base terraingen, at which point nbt can't be used yet. BO's are spawned during population, and do support nbt data. It is not advised to use nbt data very frequently though, due to performance. The features we have allow you to use blocks with nbt data sparingly, so they can be spawned in specific locations where desired. Atm we don't intend to add features that would allow you to replace blocks en-masse and include nbt data, as that would likely just blow up in most cases anyway.
