### ISSUE TITLE
OTG + StructPro: Cannot generate a world

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [PG85/OpenTerrainGenerator#7]
https://github.com/ternsip/StructPro/issues/15#issuecomment-296475987

Please talk to author for more details as I do not code.

**Comment by PG85** [comment]
Thanks, will add this to the mod compatibility issues list at https://www.reddit.com/r/openterraingen/comments/67uzha/mod_compatibility_bugs_report_them_here/ and loot at it asap,

**Comment by PG85** [comment]
This may be fixed with v18. A dev version of v18 is available here: <outdated, see next comment>

Please give it a try and tell me if that fixes the problems.

*A few notes for this version:

Should fix a whole bunch of dimension related bugs, mostly when creating/deleting dimensions and relogging and/or restarting the server. May also solve some biome registration related bugs when used with other mods that add biomes. Portal mechanics have been overhauled, dimensions should work much better now and each world can have its own portal frame materials defined in the worldconfig.

If you test the release and use the Dimensions pre-set or create/delete your own dimensions using /otg dim -l, /otg dim -c and /otg dim -d you'll want to change the portal material for each dimension in the world config. Otherwise they will all default to quartz and you'll only be able to visit the first two dimensions via a quartz portal.

**Comment by PG85** [comment]
The official v18 is now available here: https://minecraft.curseforge.com/projects/open-terrain-generator/files/2419946. It contains a few more fixes than the one I linked to before.
