### ISSUE TITLE
Bug: 1.16 - issues with objects and structures

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#752]
- Entity() not working
- NBT not working on objects (even for chests, which work for structures)
- NBT not working on anything other than chests in structures (e.g. flower pots, furnaces, dispensers, signs, cauldrons, etc)

**Comment by BiomeBundle** [comment]
DOUBLE_PLANT:2 is supposed to be double_tall_grass but isnt

**Comment by BiomeBundle** [comment]
Normal skulls generating as wither skulls

**Comment by BiomeBundle** [comment]
"Could not parse block STAINED_GLASS_PANE, substituting with air"

**Comment by FrankTCA** [comment]
Got 'er done

**Comment by PG85** [comment]
Still TODO:
- Entity (forge done, spigot still todo)
- DOUBLE_PLANT:2 is supposed to be double_tall_grass but isnt
- Normal skulls generating as wither skulls
- "Could not parse block STAINED_GLASS_PANE, substituting with air" * Fixed

**Comment by PG85** [comment]
TODO

- Will need to fix double plants in bo's via /otg edit, as they were one block before, but are now two. Doors / beds should also be looked at, not sure if they were picked up with connecting blocks fixes. * Fixed

- Grass(), Plant() and UnderWaterPlant() recognise the list of aliases for PlantType, so can spawn double plants. SurfacePatch does not use it though, so will need to, also old aliases should be automatically converted to PlantType aliases when parsing settings *except for bo's. * Fixed

- Skull may be a problem due to overlapping aliases, if I recal correctly, the old name for skull now means wither skull.

- Entity() works for Forge, Spigot has the exact same code which seems to work when inspected with breakpoints etc, but no mobs appear in the world.

- NBT for chests using numerical block/item id's should be auto-corrected to use new block/item registry names. We have not looked at nbt files using legacy block names though, those likely also need to be parsed and updated.

**Comment by authvin** [comment]
Double tall plants, doors and the like should already be fixed by /otg edit. If they're not, just need to add them to the list of blocks to update, I believe

**Comment by PG85** [comment]
Grass(), Plant(), UnderWaterPlant() and SurfacePatch() should now pick up / write back PlantType aliases, should pick up double_plant:x and minecraft:double_plant:x (case-insensitive).

**Comment by FrankTCA** [comment]
Entity() is now fixed.

**Comment by FrankTCA** [comment]
Well, this was a long one. But the last issue before 0.1.0 has been resolved! I finished it off by getting skulls and pots to work.
