### ISSUE TITLE
Cannot change World Name

### ISSUE THREAD

**Issue by RoyalReject** [PG85/OpenTerrainGenerator#90]
Currently using OpenTerrainGenerator-1.10.2-v21 already have my custom type config-ed and everything but when creating single player worlds i cannot change the world name it keeps it at the name of my generator.

**Comment by Dragnier** [comment]
Same issue in 1.12.2

**Comment by PG85** [comment]
Hey there, this is intentional, the world name must be the same as the name of your configs directory (aka the name of your preset in the world creation menu). You can clone a preset to create a world with a different name. Sorry for the inconvenience, this may seem clunky and annoying but it actually prevents far bigger problems.
