### ISSUE TITLE
Singeplayer and Lan ticks freeze completely after starting world

### ISSUE THREAD

**Issue by Gavin456b** [PG85/OpenTerrainGenerator#908]
Upon starting the game it runs normally for about 15 seconds before the world ticks freeze completely. I am still able to move around but nothing else works. 
[crash-2021-11-25_04.05.54-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/7605445/crash-2021-11-25_04.05.54-server.txt)

**Comment by PG85** [comment]
Hey @Gavin456b, thanks for reporting this. It looks like a timeout due to a single tick taking too long, so OTG may not necessarily be the culprit. I also see Lycanites in the log, we have had some reports that may be causing issues. Can you reproduce the issue reliably? We've not had any other reports of this, so can you narrow down which mod exactly is causing problems?

**Comment by Gavin456b** [comment]
I see, I saw otg mentioned a lot in the stacktrace and figured it might be the cause because i'm having trouble pinpointing it. And it began shortly after adding otg, but I will try to remove lycanites and see if that fixes it.

**Comment by Gavin456b** [comment]
Yep, disabling Lycanites fixed the issue. Thanks for your help
