### ISSUE TITLE
I Revoke the Rights to My Code

### ISSUE THREAD

**Issue by FrankTCA** [PG85/OpenTerrainGenerator#952]
Didn't know you could do this but CONTRIBUTING.md made it clear.

Hehe there was no CONTRIBUTING.md or whitepaper when I was around.

Revert all my commits please.

Oh and don't just copy the code, revert the commit, and then paste it back in.

**Comment by SXRWahrheit** [comment]
We can replace your code with additional commits, or you can open a pull request to remove code that you wish to have removed from the project so that your wishes are clearly represented by the request.

Your blog post is factually inaccurate, however; you were not even the top contributor other than PG during your tenure.

![a1239c](https://user-images.githubusercontent.com/774463/158280380-fe63aa27-de6f-4cab-84f2-e3632f1c909a.png)

Similarly, I personally do not "lie for a living" - these allegations and others like them in your post are defamatory. It is unfortunate that you have chosen to respond to merely being criticized by your colleagues for inappropriate behavior in a way that is violent and immature. That defamatory material will not be permitted on this repository, but we will honor your pull requests or otherwise replace your contributions with code that is higher-quality as represented elsewhere in the project.

**Comment by SXRWahrheit** [comment]
Sorry, one more note - there is little basis for you to claim any right to revoke your commits; the license is a shield, not a sword. As you were a collaborator on the project when you contributed and the project is designated with the MIT license, your commits are part of the project and subject to that license. Our efforts to replace your code or otherwise accept a pull request removing it are a show of good faith in response to your outburst, not an admission of ownership or other rights. Team OTG, the Repository, and PG85 retain all rights under the License to utilize contributed code.
