### ISSUE TITLE
Pull Request was not "Malicious"

### ISSUE THREAD

**Issue by FrankTCA** [PG85/OpenTerrainGenerator#954]
I didn't make the pull request "malicious". I simply didn't care enough to perfectly merge everything in.

Do it yourself if you want it done right.

I wasted nine months of my life on this project I don't want to waste another creating some perfect code removal pull request.

Revert every commit of mine. You have 24 hours before I get legal counsel involved. I want it looking like I never touched the project in the first place.

**Comment by SXRWahrheit** [comment]
The MIT license, under which you contributed to the project as an active collaborator, affords the right to use and distribute the code as desired. PG owns this repository and you will need to bring a case against him; none of the rest of us have any rights or responsibilities with regard to its contents or management. Additionally, the MIT license fully disclaims any warranties or liabilities associated with the use or reproduction of the project. Put simply, there were both implicit and explicit agreements that PG and the Project would have the benefit of your contributions and that you would be neither able nor willing to revoke them.

The sands of time will sweep your contributions away as they are replaced with new authorship - you don't need to worry about that.

If you do decide to attempt to sue PG, your lawyer will probably advise you of the following provision of the DMCA, which provides your sole potential remedy: https://en.wikipedia.org/wiki/Online_Copyright_Infringement_Liability_Limitation_Act#%C2%A7_512(f)_Misrepresentations

You knew or should have known that you were voluntarily contributing to this repository and that it was governed by the MIT license and that your rights were affected (and bound) by that license at the time of contribution. Attempting to claim otherwise after the fact does not afford you new or additional rights that did not and do not exist.

Good luck with your future endeavors in the Minecraft community - I hope you find success and happiness.
