### ISSUE TITLE
Support for Forge clients without OTG

### ISSUE THREAD

**Issue by BrainStone** [PG85/OpenTerrainGenerator#98]
Support for Forge clients without OTG would be highly apprechiated. Like Vanilla clients can connect to a Forge Server with OTG just fine. But Forge clients without it can't, as they get send data that is invalid. I suggest checking if the mod is installed client side and if not, they are handled like vanilla clients.

**Comment by PG85** [comment]
Hey, thanks for reporting. Sorry to have to disappoint you but since the dimension features for Forge were introduced OTG is required on the client or players will encounter bugs when travelling between dimensions. I've made sure you get a mod rejection message now instead of an error, that's at least a bit nicer.

**Comment by BrainStone** [comment]
Would it be possible to have an option to allow them regardless of the dimensions issue? Because I just want to use it for Biome Bundle and we have encountered several players with Forge that cannot connect because they don't have it. But we don't use any custom dimensions.
